Initial discussion revisions
DataVoke/javascript-style-guide pull request #2
Opened 2022-04-28 13:42 UTC by almercier

- Removes Airbnb specific and random unnecessary stuff from the readme
- Modifies the readme to include the amendments discussed with the team
- Creates an entry file that exports the eslint config with the amended eslint rules
- Modifies package.json for our org, and prep for npm package publish

PR recreated due to old workflow actions blocking the PR

2022-04-29 14:01 UTC, almercier commented
Ignore the status check failure, it should go away for future PRs once this is merged. I can override the status check.

2022-05-03 16:31 UTC, lzbrady requested changes

2022-05-03 16:31 UTC, lzbrady commented on README.md
> +# CAI TEch JavaScript Style Guide
```suggestion
# CAI Tech JavaScript Style Guide
```

2022-05-03 16:33 UTC, lzbrady approved these changes

2022-05-03 16:34 UTC, merged